development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: kolbykalafut@gmail.com
  :password: mypassword
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: kolbykalafut@gmail.com
  :password: mypassword
  :enable_starttls_auto: true
