# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4a2923121ac87864d45d7db0770ba9b9b17d133e591bff9e063fc2e7c5a5e01510085666ca3948660414e98fd5e2cac1ce2bf5b994eb4551a06192946969be77

test:
  secret_key_base: 37fcf5a7f1b8f10ef621092d9ffc0eb11af7496b2a899d659dc3f651b60e2dbbea2197b2e492129bd8d0587faf5d82d92fda8b9010695f649c8af5802ed26774

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
